# Download nexcloud archive and copy extract it in the server folder
- name: mkdir /srv/html
  file: path=/srv/html state=directory

- name: Download nextcloud
  unarchive:
    src: https://download.nextcloud.com/server/releases/nextcloud-12.0.0.tar.bz2
    dest: /srv/html
    group: www-data
    owner: www-data
    remote_src: true

- name: Setup nextcloud
  become_user: www-data
  command: |
      php occ maintenance:install --database "pgsql"
      --database-host "{{ ansible_hostname }}"
      --database-name "{{ nextcloud_db_name }}"
      --database-user "{{ nextcloud_db_login}}"
      --database-pass "{{ nextcloud_db _pass }}"
      --admin-user "{{ nextcloud_admin_name }}"
      --admin-pass "{{ nextcloud_admin_pass }}"
      --data-dir " {{ nextcloud_data_dir }}"
  args:
    chdir: /srv/html/nextcloud
