- name: "Install php7-gd"
  apt: name={{ item }} state=present
  with_items:
    - php7.0-gd
    - php7.0-json
    - php7.0-pgsql
    - php7.0-curl
    - php7.0-mbstring
    - php7.0-intl
    - php7.0-mcrypt
    - php-imagick
    - php7.0-xml
    - php7.0-zip

  notify:
    - Restart lighttpd
    - Enable fastcgi
    - Enable fastcgi-php

