
---
# Install lighttpd
- name: "Setup lighttpd"
  hosts: all
  become: true

  tasks:
  - name: "Install lighttpd"
    apt: name=lighttpd state=present

  - name: "Install php7-cgi"
    apt: name=php7.0-cgi state=present

  - name: "Install php7.0-xml"
    apt: name=php7.0-xml state=present

  - name: "Install php7.0-gd"
    apt: name=php7.0-gd state=present
    notify:
      - Enable fastcgi
      - Enable fastcgi-php
      - Restart lighttpd

  handlers:
  - name: Enable fastcgi
    command: lighty-enable-mod fastcgi

  - name: Enable fastcgi-php
    command: lighty-enable-mod fastcgi-php

  - name: Restart lighttpd
    service: name=lighttpd state=restarted

