
---
# Install lighttpd
- name: "Setup lighttpd"
  hosts: mbwira

  become: true

  tasks:
  - name: "Install lighttpd"
    apt: name=lighttpd state=present

  - name: "Install php7-cgi"
    apt: name=php7.0-cgi state=present

  - name: "Install php6.0-xml"
    apt: name=php7.0-xml state=present

  - name: "Install php7.0-gd"
    apt: name=php7.0-gd state=present
    notify:
      - Enable fastcgi
      - Enable fastcgi-php
      - Restart lighttpd

