# Set up a database to be used by postgresql
- name: "create postgres database user: nextcloud"
  become_user: postgres
  postgresql_user:
    name: "{{ nextcloud_db_login }}"
    password: "{{ nextcloud_db_pass }}"
    state: present

- name: Create a nextcloud database
  become_user: postgres
  postgresql_db:
    name: "{{ nextcloud_db_name }}"
    owner: "{{ nextcloud_db_login }}"
