- name: "Install Build-essential python3-dev"
  become: true
  apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
  with_items:
    - build-essential
    - python3-dev
    - python3-venv

- name: "Setup a virtualenv"
  command: python3 -m venv buildbot

- name: "Install buildbot worker"
  pip:
      name: "{{ item }}"
      virtualenv: "{{ ansible_user_dir }}/buildbot"
  with_items:
      - wheel
      - setuptools
      - buildbot-worker
      - setuptools-trial

- name: "Create buildbot slave"
  command: "{{ ansible_user_dir }}/buildbot/bin/buildbot-worker create-worker
            worker {{ master_address }} example-worker pass"

