# Install nextcloud with lighttpd

- name: Configure and deploy the database server
  hosts: db-server
  become: true

  vars_files:
    - group_vars/vault
    - group_vars/vars

  roles:
    - db

- name: Configure and deploy the webserve and application code
  hosts: web-server
  become: true

  vars_files:
    - group_vars/vault
    - group_vars/vars

  roles:
    - web
